// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessPensionMicroservice.Model;

namespace ProcessPensionMicroservice.Migrations
{
    [DbContext(typeof(PentionDb))]
    [Migration("20220816052004_Intial")]
    partial class Intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProcessPensionMicroservice.Model.ProcessPension", b =>
                {
                    b.Property<string>("Aadhar")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("BankServiceCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PensionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Aadhar");

                    b.ToTable("ProcessPensions");
                });
#pragma warning restore 612, 618
        }
    }
}
